#
# Copyright (C) 2025 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#

services:
  mqtt-broker:
    command:
    - /usr/sbin/mosquitto
    - -c
    - /mosquitto-no-auth.conf
    container_name: mqtt-broker
    hostname: mqtt-broker
    image: eclipse-mosquitto:2.0.18
    network_mode: "host"
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 1883
      published: "1883"
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  barcode:
    image: barcode:dev
    build:
      context: .
      dockerfile: Dockerfile.python
    devices:
      - /dev/:/dev/
    privileged: true
    environment:
      - MQTT_URL=localhost
      - MQTT_PORT=1883
      - VID=0x05e0
      - PID=0x1200
    network_mode: "host"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/udev/rules.d:/etc/udev/rules.d