version: '3.8'

services:
  assets-downloader:
    image: assets-downloader:latest
    container_name: assets-downloader
    environment:
      - HTTP_PROXY
      - HTTPS_PROXY
      - http_proxy
      - https_proxy
      - MODELS_DIR=/data/models
      - SAMPLES_DIR=/data/sample-media
    volumes:
      - /opt/retail-assets/models:/data/models
      - /opt/retail-assets/sample-media:/data/sample-media
    command: ["/bin/bash", "-c", "/scripts/download_models.sh && /scripts/download_videos.sh"]

  pipeline-runner:
    build:
      context: ./docker
      dockerfile: Dockerfile.pipelines
    container_name: pipeline-runner
    depends_on:
      - assets-downloader
    environment:
      - MODELS_DIR=/data/models
      - SAMPLES_DIR=/data/sample-media
      - ASSETS_DIR=/opt/retail-assets
    volumes:
      - /opt/retail-assets/models:/data/models
      - /opt/retail-assets/sample-media:/data/sample-media
    command: ["/bin/bash", "/run_pipeline.sh"]
