version: '3.8'

services:
  model-downloader:
    build:
      context: ./docker
      dockerfile: Dockerfile.downloader
    container_name: model-downloader
    volumes:
      - ./data:/data
    command: ["/bin/bash", "download_models.sh"]

  pipeline-runner:
    build:
      context: ./docker
      dockerfile: Dockerfile.pipelines
    container_name: pipeline-runner
    depends_on:
      - model-downloader
    volumes:
      - ./data:/data
    command: ["/bin/bash", "run_pipeline.sh"]
