site_name: Intel® Loss Prevention Reference Package
site_url: "https://intel-retail.github.io/loss-prevention/"
repo_name: "intel-retail/loss-prevention"
repo_url: "https://github.com/intel-retail/loss-prevention"
docs_dir: ./docs_src
site_dir: ./docs
copyright: 'Copyright &copy; 2023 Intel Corporation'
use_directory_urls: false
theme:
  name: 'material'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo-white-75px.png'
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.tracking
    - search.suggest
    - search.highlight
    - navigation.top
    - toc.follow
    - toc.integrate
plugins:
  - search
repo_url: https://github.com/intel-retail/loss-prevention
repo_name: intel-retail/loss-prevention
nav:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - Advanced Settings: 'advanced.md'
  - Performance: 'performance.md'
extra_css:
  - ./stylesheets/index.css
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - ./stylesheets/branding.css
  - ./stylesheets/extra.css
extra_javascript:
  - 'https://unpkg.com/lunr/lunr.js'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
     pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
extra:
  version:
    provider: 'mike'
