name: Build docker images

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main


permissions:
  contents: read

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Update Sub Module Performance-Tools
            run: make update-submodules
          - name: Download the Models
            run: make download-models
          - name: Build the Pipeline Runner
            run: make build-pipeline-runner
          - name: Run the Pipeline Runner
            run: make run-pipeline-runner
  
